### ISSUE TITLE
Calculating the Delay time

### ISSUE THREAD

**Issue by fwahl711** [coronafighter/coronaSEIR#1]
Hey thanks for the great work first of all. I wanted to ask how you calculate the delay time (dataOffset in main_coronaSEIR.py)? I am looking for the info on Germany.

**Comment by coronafighter** [comment]
Thanks. The offset is just manually set to match. I plan to match automatically to deaths which should be relatively precise.  
  
You might want check out this German article and the links: https://www.spiegel.de/wissenschaft/medizin/corona-krise-lockdown-koennte-bis-ins-naechste-jahr-dauern-a-ea2e318b-b388-4ccc-8493-318f892381b8

**Comment by coronafighter** [comment]
Automatic offset by matching the deaths curve is now implemented using simple root mean squared minimizing. With countries the match could still need improvement though.
