### ISSUE TITLE
Beta parameter estimate

### ISSUE THREAD

**Issue by benisonp** [coronafighter/coronaSEIR#3]
Hi, just wanted to say great work here! I did want to ask where you obtained the beta parameter estimate from?

**Comment by coronafighter** [comment]
Thanks. Initially it was way too high because I had some of the other parameters wrong. I guess Ferguson's latest estimate of three should be about right, a lot of others are close to that, too. Note that currently there is still something wrong with the numbers, I will fix it later today.
