### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by cptolemy** [coronafighter/coronaSEIR#5]
Good evening

I try to run the script, but I get allways the error **"IndexError: list index out of range"** in line 52 in world_data.py

Any idea why?

Cheers

Kepler

**Comment by coronafighter** [comment]
It should be fixed as of https://github.com/coronafighter/coronaSEIR/commit/2f3fed30c2d4c219ee68edbe677e51c089ad7313  Maybe you need to update using `git pull origin master` - warning this might overwrite any local changes.
